name: Copy File from Extended Repo

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.email "61996354+maximuslotro@users.noreply.github.com"
        git config --global user.name "maximuslotro"

    - name: Clone private repository
      env:
        PAT: ${{ secrets.EXTENDED_REPO_CODE }}
      run: |
        git clone https://maximuslotro:${PAT}@github.com/maximuslotro/LotrRenewedExtended.git private-repo
        git checkout main  # Ensure we are on the main branch

    - name: Find latest commit for en_us.json
      id: get-commit
      run: |
        cd private-repo
        COMMIT_HASH=$(git log -n 1 --pretty=format:%H -- src/generated/resources/assets/lotrextended/lang/en_us.json)
        echo "commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT

    - name: Check if commit hash has changed
      id: check-commit
      run: |
        PREVIOUS_COMMIT_HASH=${{ vars.LASTENUSCOMMENT }}
        CURRENT_COMMIT_HASH=${{ steps.get-commit.outputs.COMMIT_HASH }}
          if [ "$PREVIOUS_COMMIT_HASH" != "$CURRENT_COMMIT_HASH" ]; then
            echo "Commit hash has changed. Proceeding with file push."
            gh variable set LASTENUSCOMMENT --body "testvariavle"
          else
            echo "Commit hash has not changed. Skipping."
            exit 0  # Exit successfully without further actions
          fi
      env:
        GITHUB_TOKEN: ${{ secrets.EXTENDED_LANG_REPO_CODE }}

    - name: Copy file
      run: |
        mkdir -p langs/upstream/
        cp private-repo/src/generated/resources/assets/lotrextended/lang/en_us.json langs/upstream/en_us.json

    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        clean: false

    - name: Check for existing PR
      id: pr-check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_URL=$(gh pr list --head maximuslotro:update-from-private-lang --json url --jq '.[0].url' || echo "none")
        echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT

    - name: Create or update pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME="update-from-private-lang"
        COMMIT_HASH=${{ steps.get-commit.outputs.commit_hash }}
        git checkout $BRANCH_NAME
        git pull origin $BRANCH_NAME # Pull latest update branch changes
        git add langs/upstream/en_us.json
        git commit -m "Copied en_us.json from private repo, latest edit commit: $COMMIT_HASH"
        git push origin $BRANCH_NAME
        # PR_URL=${{ steps.pr-check.outputs.pr_url }}
        # if [ "$PR_URL" = "none" ]; then
          # gh pr create --title "Update en_us.json" --body "Copied en_us.json from private repo, latest edit commit: $COMMIT_HASH" --head $BRANCH_NAME --base main
        # else
          # gh pr edit "$PR_URL" -body "Copied en_us.json from private repo, latest edit commit: $COMMIT_HASH"
        # fi
