name: Copy File from Extended Repo

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.email "61996354+maximuslotro@users.noreply.github.com"
        git config --global user.name "maximuslotro"

    - name: Clone private repository
      env:
        PAT: ${{ secrets.EXTENDED_REPO_CODE }}
      run: |
        git clone https://maximuslotro:${PAT}@github.com/maximuslotro/LotrRenewedExtended.git private-repo
        git checkout main  # Ensure we are on the main branch

    - name: Find latest commit for en_us.json
      id: get-commit
      run: |
        cd private-repo
        COMMIT_HASH=$(git log -n 1 --pretty=format:%H -- src/generated/resources/assets/lotrextended/lang/en_us.json)
        echo "::set-output name=commit_hash::$COMMIT_HASH"

    - name: Copy file
      run: |
        mkdir -p upstream/langs/
        cp private-repo/src/generated/resources/assets/lotrextended/lang/en_us.json upstream/langs/en_us.json
      
    - name: Push changes
      run: |
        COMMIT_HASH=${{ steps.get-commit.outputs.commit_hash }}
        git add upstream/langs/en_us.json
        git commit -m "Copied en_us.json from private repo, latest edit commit: $COMMIT_HASH"
        git push origin main
