name: Copy File from Extended Repo

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.email "61996354+maximuslotro@users.noreply.github.com"
        git config --global user.name "maximuslotro"

    - name: Clone private repository
      env:
        PAT: ${{ secrets.EXTENDED_REPO_CODE }}
      run: |
        git clone https://maximuslotro:${PAT}@github.com/maximuslotro/LotrRenewedExtended.git private-repo
        git checkout main  # Ensure we are on the main branch

    - name: Find latest commit for en_us.json
      id: get-commit
      run: |
        COMMIT_HASH=$(git log -n 1 --pretty=format:%H -- private-repo/src/generated/resources/assets/lotrextended/lang/en_us.json)
        echo "commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT

    - name: Check if commit hash has changed
      id: check-commit
      run: |
        HASH_FILE="langs/upstream/hashes/en_us_hash.txt"
        if [ -f "$HASH_FILE" ]; then
          PREVIOUS_COMMIT_HASH=$(cat "$HASH_FILE")
          CURRENT_COMMIT_HASH=${{ steps.get-commit.outputs.COMMIT_HASH }}
          if [ "$PREVIOUS_COMMIT_HASH" != "$CURRENT_COMMIT_HASH" ]; then
            echo "Commit hash has changed. Proceeding with file push."
            echo "$CURRENT_COMMIT_HASH" > "$HASH_FILE"  # Update the commit hash file
          else
            echo "Commit hash has not changed. Skipping file push."
            exit 0  # Exit successfully without further actions
          fi
        else
          echo "Hash file does not exist. Creating and saving current commit hash."
          mkdir -p langs/upstream/hashes/
          echo "${{ steps.get-commit.outputs.COMMIT_HASH }}" > "$HASH_FILE"
        fi

    - name: Copy file
      run: |
        mkdir -p langs/upstream/
        cp private-repo/src/generated/resources/assets/lotrextended/lang/en_us.json langs/upstream/en_us.json

    - run: ls

    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        clean: false

    - run: ls

    - name: Push changes
      run: |
        COMMIT_HASH=${{ steps.get-commit.outputs.commit_hash }}
        git add langs/upstream/en_us.json
        git commit -m "Copied en_us.json from private repo, latest edit commit: $COMMIT_HASH"
        git push origin main